name: firn_dbt_project
version: 1.0.0
config-version: 2

profile: default

model-paths: ["models"]

models:
  firn_dbt_project:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    marts:
      +materialized: table
    metrics:
      +enabled: false
