select
    variant_col:"OBJECTID"::varchar as object_id,
    variant_col:"GlobalID"::varchar as global_id,
    variant_col:"NAME"::varchar as station_name,
    variant_col:"ADDRESS"::varchar as address,
    variant_col:"OPERATOR"::varchar as operator,
    variant_col:"OWNER"::varchar as owner,
    variant_col:"Type"::varchar as type,
    variant_col:"currentType"::varchar as current_type,
    try_to_number(variant_col:"carParkCount"::varchar) as car_park_count,
    try_to_number(variant_col:"numberOfConnectors"::varchar) as number_of_connectors,
    try_to_double(variant_col:"latitude"::varchar) as latitude,
    try_to_double(variant_col:"longitude"::varchar) as longitude,
    try_to_date(variant_col:"dateFirstOperational"::varchar, 'DD/MM/YYYY') as date_first_operational,
    variant_col:"connectorsList"::varchar as connectors_list,
    variant_col:"maxTimeLimit"::varchar as max_time_limit,
    variant_col:"hasCarparkCost"::varchar as has_carpark_cost,
    variant_col:"hasChargingCost"::varchar as has_charging_cost,
    variant_col:"hasTouristAttraction"::varchar as has_tourist_attraction,
    variant_col:"is24Hours"::varchar as is_24_hours
from FIRN_PROJECT.LANDING.EV_ROAM_CHARGING_STATIONS_JSON